FROM golang:1.13-alpine as builder
WORKDIR /app
RUN  /bin/sed -i 's,http://dl-cdn.alpinelinux.org,https://mirrors.aliyun.com,g' /etc/apk/repositories
RUN  apk add --no-cache gcc musl-dev
COPY main.go /app/main.go
RUN go build -ldflags "-linkmode external -extldflags -static" main.go

FROM alpine:3.10
WORKDIR /app
COPY --from=builder /app/main  /app/main
CMD [ "/app/main" ]
